apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: dnsmasq-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: dnsmasq:latest
  source:
    git:
      uri: https://github.com/richmitch/ocp-dhcp
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag
        name: tools:latest
        namespace: openshift
      env:
        - name: BUILD_LOGLEVEL
          value: '2'
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChange:
      from:
        kind: ImageStreamTag
        name: tools:latest
        namespace: openshift