kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dnsmasq-dhcp-leases-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-sc
  volumeMode: Filesystem