---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq-dhcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsmasq-dhcp
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "multus-network",
              "interface": "eth1",
              "ips": ["192.168.1.100/24"]
            }
          ]
      labels:
        app: dnsmasq-dhcp
    spec:
      containers:
      - name: dnsmasq
        image: image-registry.openshift-image-registry.svc:5000/dnsmasq/dnsmasq:latest
        imagePullPolicy: IfNotPresent
        command: ["dnsmasq", "-d"]
        ports:
        - name: dhcp
          containerPort: 67
          protocol: UDP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: dnsmasq-conf
          mountPath: /etc/dnsmasq.conf
          subPath: dnsmasq.conf
        - name: leases
          mountPath: /var/lib/dnsmasq
      volumes:
      - name: dnsmasq-conf
        configMap:
          name: dnsmasq-dhcp
      - name: leases
        emptyDir: {}          
