apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-dhcp
data:
  dnsmasq.conf: |
    dhcp-range=192.168.0.50,192.168.0.150,12h
    dhcp-option=option:router,192.168.0.1
    dhcp-option=option:dns-server,8.8.8.8,8.8.4.4
