---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq-dhcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsmasq-dhcp
  template:
    metadata:
      labels:
        app: dnsmasq-dhcp
    spec:
      containers:
      - name: dnsmasq
        image: image-registry.openshift-image-registry.svc:5000/dnsmasq/dnsmasq:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        ports:
        - name: dhcp
          containerPort: 67
          protocol: UDP
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: dnsmasq-conf
          mountPath: /etc/dnsmasq.conf
          subPath: dnsmasq.conf
      volumes:
      - name: dnsmasq-conf
        configMap:
          name: dnsmasq-dhcp
