apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-dhcp
data:
  dnsmasq.conf: |
    dhcp-range=192.168.100.100,192.168.100.150,24h
    dhcp-option=option:router,192.168.100.1
    dhcp-option=option:dns-server,192.168.20.20
