kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: dhcp

bases:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: dhcp
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0